name: underwater_video_tagging
description: Marine Life Identifier
publish_to: 'none'
version: 0.4.2+20

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  ffmpeg_kit_flutter: ^6.0.3
  flutter_tags_x: ^1.1.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  file_picker: ^8.0.7
  uuid: ^4.4.2
  auto_size_text: ^3.0.0
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  another_flushbar: ^1.12.30
  mime: ^1.0.5
  image: ^4.2.0
  tflite_flutter:
    path: ../../flutter-tflite
  connectivity_plus: ^6.0.5
  crypto: ^3.0.5
  photo_view: ^0.15.0
  multi_select_flutter: ^4.1.3
  chewie: ^1.8.3
  video_thumbnail: ^0.5.3
  cached_network_image: ^3.4.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_cache_manager: ^3.4.1
  video_player: ^2.9.1
dev_dependencies:
  dependency_validator: ^4.1.0
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: graphics/icon/ic_launcher_xxxhdpi.png
  image_path_ios: graphics/icon/ic_launcher_xxxhdpi.png
  adaptive_icon_background: graphics/icon/ic_background.png
  adaptive_icon_foreground: graphics/icon/ic_foreground.png